project:
  type: website
  output-dir: "docs"

website:
  title: "NFL Win Probability"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Visualizations
        href: viz.qmd
      - text: Report
        href: Final.qmd
  page-footer:
    center: "Copyright &copy; 2026 Shannon Tanoto"

format:
  html:
    theme: cosmo
    highlight-style: textmate
    css: styles.css