---
title: "Midterm Project"
format:
    html
jupyter: python3
---

**GITHUB LINK:** <https://github.com/tanotosh/JSC370_project.git>

# INTRODUCTION

The aim of this project is to explore how likely an NFL (National Football League) team is going to win a game given the current game statistics. Specifically, this project examines the influences of variables such as field position, time remaining, and score difference on the game's outcome throughout the game. Additionaly, our model will take into account the offensive and defensive team performance based on historical patterns of how each respective teams perform in specific game situations. Theses variables are the foundations for training a machine learning model that estimates the win probability on a play-by-play basis during an NFL game.

# METHODS

## Data Collection

The dataset was extracted using the ESPN Public API. To start, the API was used to collect all NFL games from the 2022 season, providing a dataset containing 336 games with 3 variables.

#### Games Dataset:

-   id: Game ID number

-   name: Game name

-   date: Game date

Next, a second ESPN Public API was used to retrieve play-by-play data that occurred in each game of the 2022 season. This produced a dataset of 57,547 observations (or single plays) with 13 variables including several game statistics.

#### Plays Dataset:

-   gid: Game ID number

-   pid: Play ID number

-   play_action: Description of play

-   quarter: Quarter in which the play occurred

-   time_remaining: Time remaining in the current quarter (in seconds)

-   down: Down in which play was done

-   yards_to_go: Yards needed to get a first down

-   yardsToEndzone: Yards needed to get a touchdown/the endzone

-   yards_gained: Yards gained on play

-   home_score: Home team's current score

-   away_score: Away's team current score

-   offense_team: Offensive team's ID number

-   defense_team: Defensive team's ID number

```{python}
#| echo: false
#| #import libaries
import requests
import pandas as pd
import json
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import time
from plotnine import *
```

```{python}
#| echo: false
# ESPN API configuration
BASE_URL = "https://site.api.espn.com/apis/site/v2/sports/football/nfl/"

# Extract NFL 2022 season games
games = []
url = f"{BASE_URL}scoreboard"

params = {
    "limit": 1000,
    "dates": 2022
}

response = requests.get(url, params = params)

data = response.json()

for event in data["events"]:
    games.append({
        "id": event['id'],
        "name": event["name"],
        "date": event["date"]
    })

df_games = pd.DataFrame(games)
```

```{python}
#| echo: false
df_games.head(50)
df_games.info()
```

```{python}
#| echo: false
#Extract Play-by-play
plays = []
for gid in df_games['id']:
    url = f"https://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events/{gid}/competitions/{gid}/plays"

    params = {
        "limit": 300
    }

    response = requests.get(url, params = params)

    data = response.json()

    for play in data.get("items",[]):
        offense_team = None
        defense_team = None
        for team in play.get('teamParticipants',[]):
            if team.get('type') == 'offense':
                offense_team = team.get('id')

            elif team.get('type') == 'defense':
                defense_team = team.get('id')


        plays.append({
            "gid": gid,
            "pid": play.get('id'),
            "play_action": play.get("text", ""),
            "quarter": play.get('period',{}).get('number'),           
            "time_remaining": play.get('clock',{}).get('value'),
            "down": play.get('start', {}).get('down'),
            "yards_to_go": play.get('start',{}).get('distance'),
            "yardsToEndzone": play.get('start', {}).get('yardsToEndzone'),
            "yards_gained": play.get("statYardage"),
            "home_score" : play.get("homeScore"),
            "away_score": play.get('awayScore'),
            "offense_team": offense_team,
            "defense_team": defense_team

        })

        time.sleep(0.1)

    print(f"{gid}")

df_plays = pd.DataFrame(plays)
```

```{python}
#| echo: false
df_plays.to_csv("nfl_plays_2022.csv", index = False)
```

## Data Cleaning & Wrangling

```{python}
#| echo: false
df_plays.describe() #check for extreme data
missing = df_plays.isna().sum().to_frame("n_missing")
missing["pct_missing"] = (missing['n_missing']/len(df_plays)).round(4)
missing.sort_values("pct_missing", ascending=False).head(20) #check for missing data
```

Based on the summary table of missing data, we observe that most variables in the plays dataset don't have any missing values. The only variables with missing vales are offense_team and defense_team.

Further investigation of these observations shows that these values are missing when the play occurred at the start or end of a quarter or game (indicated by variable play_action). Since these plays don't represent standard plays, they are not relevant for our model and thus are filtered out.

Moreover, after examining the summary statistics table, we see that all variables are within the reasonable ranges:

-   home_score and away_score are positive (minimums are 0)

-   yards_gained has a range within -109 and 109 yards, which is the maximum length of a football field including the end zones

-   time_remaining between 0 and 900 which is 4 quarters of 15 minutes

-   yards_to_go and yardsToEndzone are positive and under 100 yards, reflecting the maximum possible distance of a football field

However, the summary statistics table also show a minimum values of 0 for variables: down and quarter. After examining these observations, we see that these plays corresponds to kickoffs or start of a game. Because these events don't represent standard play, we keep entries with quarter 1,2,3,4 and 5 (representing the 4 quarters of a standard NFL game and overtime), as well as downs 1,2,3,4 (representing offensive downs)

```{python}
#| echo: false
df_plays_a = df_plays[df_plays['down']==0]
#display(df_plays_a)

#shows that when downs = 0 => kickoff/start of game

df_plays_b = df_plays[df_plays['quarter']==0]
#display(df_plays_b)

#shows that when quarter = 0 => start of game

df_plays_c = df_plays[df_plays['offense_team'].isna()]
#display(df_plays_c)

#shows that when offense_team = 0 => start/end of quarter or game

df_plays_d = df_plays[df_plays['defense_team'].isna()]
#display(df_plays_d)

#shows that when defense_team = 0 => start/end of quarter or game
```

```{python}
#| echo: false
# check if quarter is either 1, 2, 3, 4
df_plays = df_plays[df_plays['quarter'].isin([1,2,3,4,5])]
# check if down is 1,2,3,4
df_plays = df_plays[df_plays['down'].isin([1,2,3,4])]
# offense and defense team is not null
df_plays = df_plays.dropna(subset=["offense_team", "defense_team"])

df_plays.info()
```

After filtering out irrelevant data, our dataset contains 52,410 meaningful plays across all games.

## Feature Engineering

In order to better represent the state of the game, two additional variables were engineered from existing data:

-   gametime_remaining: Time remaining in the game (in seconds)

    -   This was calculated by taking the number of quarters remaining multiplied by 900 seconds (which is 15 minutes) and adding the remaining time in the current quarter.
    -   And set it to NULL for overtime plays

-   score_diff: Score Difference between home and away team (relative to the home team)

    -   This was measured by the difference between the home team's score and away team's score at that time of play

```{python}
#| echo: false
#Feature Engineering
#Adding variable of time remaning in game instead of in quarter
df_plays["gametime_remaining"] = np.where(df_plays['quarter']<=4, (4-df_plays['quarter'])*900 + df_plays['time_remaining'], np.nan)

#Adding Score Difference relative to home team
df_plays["score_diff"] = (df_plays["home_score"] - df_plays['away_score'])

df_plays.info()
df_plays.describe()
```

# PRELIMINARY RESULTS

## Summary Statistics

The summary table below shows key game statistics of 52,410 plays from the 2022 NFL season with each observation representing a single play including variables describing the game situation.

|   | quarter | time_remaining | down | yards_to_go | yardsToEndzone | yards_gained | home_score | away_score | gametime_remaining | score_diff |
|----|----|----|----|----|----|----|----|----|----|----|
| mean | 2.59 | 407.24 | 2.02 | 8.41 | 51.36 | 5.77 | 11.72 | 10.17 | 1696.95 | 1.55 |
| std | 1.13 | 275.30 | 1.01 | 4.12 | 24.42 | 10.43 | 9.67 | 9.16 | 1050.37 | 9.633 |
| min | 1 | 0 | 1 | 1 | 0 | -45 | 0 | 0 | 0 | -37 |
| max | 5 | 900 | 4 | 89 | 99 | 99 | 54 | 51 | 3600 | 47 |

## Exploratory Data Analysis

```{python}
#| echo: false
# Counts of Plays per quarter
(ggplot(df_plays, aes(x='factor(quarter)', fill='factor(down)')) +
geom_bar()+
labs(
    x='Quarter',
    y = "Number of Plays",
    fill = "Down",
    title = "Proportion of Downs per Quarters"
) + 
theme_minimal()
)
```

This stacked bar graph displays the number of plays as well as the proportion of downs across each quarter. We can see that there are more plays occurring in second and fourth quarter. Besides that, first and second down occurs more frequent compared to third and fourth down. Notice how there is more fourth down played in the fourth quarter compared to other quarters suggesting increased risk-taking drives attempted by teams. Another thing to highlight, is the low count in plays for 5th quarter as overtime don't happen often in NFL games.

```{python}
#| echo: false
# Distribution of Time Remaining in each quarter
(ggplot(df_plays, aes(x='factor(quarter)', y='time_remaining')) +
geom_boxplot()+
labs(
    x = "Time Remaining in Quarter (in seconds)",
    y = "Quarters",
    title = "Distribution of Time Remaining per Quarter"
) + 
theme_minimal()
)
```

The distribution of time remaining within each quarter is balanced with plays occurring throughout the duration of the game. This suggests that plays are not are not concentrated in a certain time of the quarter and that our data is not skewed.

```{python}
#| echo: false
#Distribution of Yards To Endzone
plt.hist(df_plays["yardsToEndzone"], bins=100)
plt.xlabel("Yards to Enzone")
plt.ylabel("Count")
plt.title("Distribution of Yards To Endzone")
plt.show()
```

Field position values are distributed across the field with more plays occurring at approximately 75 yards away from the end zone where most drives often begin.

```{python}
#| echo: false
# Association between GameTime Remaining and Score Difference
(ggplot(df_plays, aes(x='gametime_remaining', y='score_diff')) +
geom_point(alpha=0.5)+
labs(
    x='Gametime Remaining (in Seconds)',
    y = "Score Difference (relative to Home team)",
    title = "Association between GameTime Remaining and Score Difference"
) + 
theme_minimal()
)
```

The association between the score difference and game time remaining seems to have a correlation where as game time decreases, the score differences tend to increase, reflecting the fact that games often become more decisive towards the end.

# SUMMARY

The exploratory analysis highlights several patterns in the data that are relevant for predicting game outcomes. The variables describe immediate context of each play and together it captures the overall game state at any point of time in a game.

In the final stage of this project, a machine learning model will be trained using the plays dataset. The variables selected will be used as input features to estimate the probability that a team wins the game given the current game state, as well as the difference in the offense and defense team performance. Then, model will be evaluated using a test dataset which will be the 2023 NFL season games play by play dataset. The model will be assessed using an accuracy score.

The results of the model will be illustrated on an interactive website, where win probability graphs are updated after each play. Additional visualizations such as possession time, number of first downs achieved, and a updated game stats table will also be displayed to provide further analysis of game progression.
