<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Shannon Tanoto’s Final Project – NFL Win Probability</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6008737dd99a25fb026f31e622d6b0f8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">NFL Win Probability</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./viz.html"> 
<span class="menu-text">Visualizations</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./Final.html" aria-current="page"> 
<span class="menu-text">Report</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        
    <div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="Final.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Shannon Tanoto’s Final Project</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>INTRODUCTION</h1>
<p>The aim of this project is to build a machine learning model that predicts the probability that a home team is going to win an NFL (National Football League) game given a current game state (features). A game state is described by statistics of a team’s field position (yards to go, yards to endzone, yards gained), game’s time remaining (quarter, time_remaining), and the score difference(home score, away score). Another key feature is the offensive and defensive team strengths based on each team’s historical performance (offense strength and defense strength). All of these variables capture both the immediate context of the game and the relative strengths of the teams, and are leveraged by the model to predict the win probability (model’s output). A binary target outcome, whether the home team wins the game, contributes to the model training as well. The model is trained on past data to predict the win probability at any point of time in the game, which can be valuable for fans, analysts, coaches or strategists seeking to better understand the game dynamics, evaluate team performance, and support real-time decision making in sports analytics.</p>
</section>
<section id="methods" class="level1">
<h1>METHODS</h1>
<section id="data-collection" class="level2">
<h2 class="anchored" data-anchor-id="data-collection">Data Collection</h2>
<p>The dataset was extracted using the ESPN Public API (https://github.com/pseudo-r/Public-ESPN-API). To start, the API was used to collect all NFL games from the 2022 and 2023 season, providing two datasets containing 336 games and 349 games respetively with 5 variables:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
<th>Type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>id</td>
<td>Game ID number</td>
<td>String</td>
</tr>
<tr class="even">
<td>name</td>
<td>Game’s name (teams playing)</td>
<td>String</td>
</tr>
<tr class="odd">
<td>home_team</td>
<td>Home team’s ID number</td>
<td>String</td>
</tr>
<tr class="even">
<td>away_team</td>
<td>Away team’s ID number</td>
<td>String</td>
</tr>
<tr class="odd">
<td>date</td>
<td>Game’s date</td>
<td>String</td>
</tr>
</tbody>
</table>
<p><strong>Table 1: Games Dataset</strong></p>
<p>Next, a different endpoint of the ESPN Public API was used to retrieve play-by-play data that occurred in each game of the 2022 and 2023 season. This produced two dataset of 57,547 observations (or single plays) and 52,703 observations respectively with 13 variables:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 64%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
<th>Type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>gid</td>
<td>Game ID number</td>
<td>Integer</td>
</tr>
<tr class="even">
<td>pid</td>
<td>Play ID number</td>
<td>Integer</td>
</tr>
<tr class="odd">
<td>play_action</td>
<td>Description of the play</td>
<td>String</td>
</tr>
<tr class="even">
<td>quarter</td>
<td>Quarter in which the play occurred</td>
<td>Integer</td>
</tr>
<tr class="odd">
<td>time_remaining</td>
<td>Time remaining in the current quarter (seconds)</td>
<td>Float</td>
</tr>
<tr class="even">
<td>down</td>
<td>Down in which the play occurred</td>
<td>Integer</td>
</tr>
<tr class="odd">
<td>yards_to_go</td>
<td>Yards needed to get a first down</td>
<td>Integer</td>
</tr>
<tr class="even">
<td>yardsToEndzone</td>
<td>Yards needed to reach the endzone</td>
<td>Integer</td>
</tr>
<tr class="odd">
<td>yards_gained</td>
<td>Yards gained on the play</td>
<td>Integer</td>
</tr>
<tr class="even">
<td>home_score</td>
<td>Home team’s current score</td>
<td>Integer</td>
</tr>
<tr class="odd">
<td>away_score</td>
<td>Away team’s current score</td>
<td>Integer</td>
</tr>
<tr class="even">
<td>offense_team</td>
<td>Offensive team ID</td>
<td>Float</td>
</tr>
<tr class="odd">
<td>defense_team</td>
<td>Defensive team ID</td>
<td>Float</td>
</tr>
</tbody>
</table>
<p><strong>Table 2: Plays Dataset</strong></p>
</section>
<section id="data-cleaning-wrangling" class="level2">
<h2 class="anchored" data-anchor-id="data-cleaning-wrangling">Data Cleaning &amp; Wrangling</h2>
<p>First, notice that games dataset’s column “id” corresponds to the plays dataset’s column “gid”. However, they have different variable types, so “gid” was converted to a string, matching “id”. Since only the plays dataset was downloaded and may not align with potential API updates for the games dataset, we filter out any games that are not in the plays dataset using the “gid” set.</p>
<p>Next, based on the summary table of missing data, we observe that most variables in the plays dataset don’t have any missing values. The only variables with missing values are offense_team and defense_team.</p>
<p>Further investigation of these observations shows that these values are missing when the play occurred at the start or end of a quarter or game (indicated by variable play_action). Since these plays don’t represent standard plays, they are not relevant for our model and thus are filtered out.</p>
<p>Moreover, after examining the summary statistics table, we see that all variables are within the reasonable ranges:</p>
<ul>
<li><p>home_score and away_score are positive (minimums are 0)</p></li>
<li><p>yards_gained has a range within -109 and 109 yards, which is the maximum length of a football field including the end zones</p></li>
<li><p>time_remaining between 0 and 900 which is 4 quarters of 15 minutes</p></li>
<li><p>yards_to_go and yardsToEndzone are positive and under 100 yards, reflecting the maximum possible distance of a football field</p></li>
</ul>
<p>However, the summary statistics table also show a minimum values of 0 for variables: down and quarter. After examining these observations, we see that these plays corresponds to kickoffs or start of a game. Because these events don’t represent standard play, we keep entries with quarter 1,2,3,4 and 5 (representing the 4 quarters of a standard NFL game and overtime), as well as downs 1,2,3,4 (representing offensive downs)</p>
<p>After filtering out irrelevant data, our datasets contains 52,410 and 48,376 meaningful plays for the training (2022) and testing (2023) datasets respectively.</p>
</section>
<section id="feature-engineering" class="level2">
<h2 class="anchored" data-anchor-id="feature-engineering">Feature Engineering</h2>
<p>The target outcome for this model is a binary indicator of whether the home team wins the game. Since the dataset is rows of all plays played in the all games, we first grouped the plays per game, and find the maximum score for both the home and away team for each game. If the home team has the higher maximum score, then the tagret outcome variable, “home_wins” is set to 1 indicating tha tthe home team won. This target outcome will then be merged into the orignal plays dataset so that each row (or play) is assinged the final game outcome.</p>
<p>In order to better represent the state of the game, 4 additional variables were engineered from existing data:</p>
<ul>
<li><p>gametime_remaining: Time remaining in the whole game (instead of time remaining in the quarter as represented as the variable time_remaning) (in seconds)</p>
<ul>
<li><strong>gametime_remaining</strong> = ((4 - quarters) x 900) + time_remaining</li>
<li>where each quarter consists of 900 seconds ( = 15 minutes) and for quarter = 5 (indicating overtime plays), this value is set to NULL</li>
</ul></li>
<li><p>score_diff: Score Difference between home and away team (relative to the home team)</p>
<ul>
<li><strong>score_diff</strong> = home_score - away_score</li>
<li>the difference between the home team’s score and away team’s score at that time of play</li>
</ul></li>
<li><p>offense_strength: the strength of the team currently on offense</p>
<ul>
<li>This value was calculated by the sum of wins / sum of games played per team</li>
</ul></li>
<li><p>defense_strength: the strength of the team currently on defense</p>
<ul>
<li>This value was calculated by the sum of wins / sum of games played per team</li>
</ul></li>
</ul>
<p>Together, these engineered varaibles provide more context of the game, improving the model’s training to estimate the win probability.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 28%">
<col style="width: 58%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
<th>Type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>gid</td>
<td>Game ID</td>
<td>String</td>
</tr>
<tr class="even">
<td>pid</td>
<td>Play ID</td>
<td>Integer</td>
</tr>
<tr class="odd">
<td>play_action</td>
<td>Description of play</td>
<td>String</td>
</tr>
<tr class="even">
<td>quarter</td>
<td>Quarter of play</td>
<td>Integer</td>
</tr>
<tr class="odd">
<td>time_remaining</td>
<td>Time remaining in quarter (seconds)</td>
<td>Float</td>
</tr>
<tr class="even">
<td>down</td>
<td>Current down</td>
<td>Integer</td>
</tr>
<tr class="odd">
<td>yards_to_go</td>
<td>Yards to first down</td>
<td>Integer</td>
</tr>
<tr class="even">
<td>yardsToEndzone</td>
<td>Distance to endzone</td>
<td>Integer</td>
</tr>
<tr class="odd">
<td>yards_gained</td>
<td>Yards gained on play</td>
<td>Integer</td>
</tr>
<tr class="even">
<td>home_score</td>
<td>Home team score</td>
<td>Integer</td>
</tr>
<tr class="odd">
<td>away_score</td>
<td>Away team score</td>
<td>Integer</td>
</tr>
<tr class="even">
<td>offense_team</td>
<td>Offensive team ID</td>
<td>String</td>
</tr>
<tr class="odd">
<td>defense_team</td>
<td>Defensive team ID</td>
<td>String</td>
</tr>
<tr class="even">
<td>gametime_remaining</td>
<td>Time remaining in game (seconds)</td>
<td>Float</td>
</tr>
<tr class="odd">
<td>score_diff</td>
<td>Home score − away score</td>
<td>Integer</td>
</tr>
<tr class="even">
<td>home_wins</td>
<td>Target variable (1 = home win, 0 = loss)</td>
<td>Integer</td>
</tr>
<tr class="odd">
<td>offense_strength</td>
<td>Offensive team win rate</td>
<td>Float</td>
</tr>
<tr class="even">
<td>defense_strength</td>
<td>Defensive team win rate</td>
<td>Float</td>
</tr>
</tbody>
</table>
<p><strong>Table 3: Final Dataset</strong></p>
</section>
<section id="eda" class="level2">
<h2 class="anchored" data-anchor-id="eda">EDA</h2>
<section id="statistics-summary-of-key-variables" class="level3">
<h3 class="anchored" data-anchor-id="statistics-summary-of-key-variables">Statistics Summary of Key Variables</h3>
<p>The summary table below shows key game statistics of 52,410 plays from the 2022 NFL season (train dataset) with each observation representing a single play including variables describing the game situation. The table confirms that all variables fall within expected ranges of a realistic game state.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>quarter</th>
<th>time_remaining</th>
<th>down</th>
<th>yards_to_go</th>
<th>yardsToEndzone</th>
<th>yards_gained</th>
<th>home_score</th>
<th>away_score</th>
<th>gametime_remaining</th>
<th>score_diff</th>
<th>home_wins</th>
<th>offense_strength</th>
<th>defense_strength</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>mean</td>
<td>2.59</td>
<td>407.24</td>
<td>2.02</td>
<td>8.41</td>
<td>51.36</td>
<td>5.77</td>
<td>11.72</td>
<td>10.17</td>
<td>1696.95</td>
<td>1.55</td>
<td>0.559</td>
<td>0.501</td>
<td>0.499</td>
</tr>
<tr class="even">
<td>std</td>
<td>1.13</td>
<td>275.30</td>
<td>1.01</td>
<td>4.12</td>
<td>24.42</td>
<td>10.43</td>
<td>9.67</td>
<td>9.16</td>
<td>1050.37</td>
<td>9.633</td>
<td>0.497</td>
<td>0.1449</td>
<td>0.1451</td>
</tr>
<tr class="odd">
<td>min</td>
<td>1</td>
<td>0</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>-45</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>-37</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>max</td>
<td>5</td>
<td>900</td>
<td>4</td>
<td>89</td>
<td>99</td>
<td>99</td>
<td>54</td>
<td>51</td>
<td>3600</td>
<td>47</td>
<td>1</td>
<td>1</td>
<td>1</td>
</tr>
</tbody>
</table>
<p><strong>Table 4: Summary Table of Key Variables</strong></p>
<div id="cf1beb37" class="cell" data-execution_count="21">
<div class="cell-output cell-output-display" data-execution_count="21">
<div>
<figure class="figure">
<p><img src="Final_files/figure-html/cell-22-output-1.png" width="384" height="240" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Figure 1: Proportion of Downs per Quarter</strong></p>
<p>This stacked bar graph displays the number of plays as well as the proportion of downs across each quarter. We can see that there are more plays occurring in second and fourth quarter which might be because teams tend to hustle as they approach a turnover or end of the game. Besides that, first and second down occurs more frequent compared to third and fourth down which is expected as they represent the start of offensive drives. Notice how there is more fourth down played in the fourth quarter compared to other quarters suggesting increased risk-taking drives attempted by teams to get more points in the limited time left. Another thing to highlight, is the low count in plays for 5th quarter as overtime don’t happen often in NFL games. Hence, these findings suggests that both downs and quarters might influence win probability and thus are added as features of the model.</p>
<div id="15c2477f" class="cell" data-execution_count="22">
<div class="cell-output cell-output-display" data-execution_count="22">
<div>
<figure class="figure">
<p><img src="Final_files/figure-html/cell-23-output-1.png" width="384" height="240" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Figure 2: Distribution of Time Remaining per Quarter</strong></p>
<p>The distribution of time remaining within each quarter is balanced with plays occurring throughout the duration of the game. This suggests that plays are not are not concentrated in a certain time of the quarter and that our data is not skewed (it captures game states at all point in time of the game) . This is key for the model as it ensures that predictions can be made across all quarters of the game.</p>
<div id="4c95bdae" class="cell" data-execution_count="23">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_files/figure-html/cell-24-output-1.png" width="602" height="449" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Figure 3: Distribution of Yards to Endzone</strong></p>
<p>Field position values are distributed across the field with more plays occurring at approximately 75 yards away from the end zone where most drives often begin. The wide spread indicates that the dataset captures a diverse range of game situation at every yard of the field, ensuring that predictions can be made by the model across the field.</p>
<div id="cd8f929a" class="cell" data-execution_count="24">
<div class="cell-output cell-output-stderr">
<pre><code>C:\Users\shnta\Desktop\JSC370_2026_Winter\.venv\Lib\site-packages\plotnine\layer.py:374: PlotnineWarning: geom_point : Removed 483 rows containing missing values.</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="24">
<div>
<figure class="figure">
<p><img src="Final_files/figure-html/cell-25-output-2.png" width="384" height="240" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Figure 4: Association between Gametime Remaining and Score Difference</strong> The association between the score difference and game time remaining seems to have a correlation where as game time decreases (game progresses), the score differences tend to increase in magnitude, reflecting the fact that games often become more decisive towards the end.</p>
</section>
</section>
<section id="model-building" class="level2">
<h2 class="anchored" data-anchor-id="model-building">Model Building</h2>
<p>To search for the best model to predict the probablity that the home team wins, both Random Forest classifier and the XGBoost Classifier were candidates, because: - Random Forest Classifer: this model creates decision trees by randomly creating subsets of the 8 key variables and takes the majority vote across the trees.</p>
<pre><code>- XGBoost Classifier: this model creates a weak learner and slightly improves sequentially upon predictions of the previous models by focusing on the observations with the largest errors</code></pre>
<p>Both approaches improves prediction accuracy for a binary target outcome, whether the team wins (indicated by home_wins = 1) or loses (indicated by home_wins = 0) and outputs the probability of a home team win.</p>
<section id="training-and-testing" class="level3">
<h3 class="anchored" data-anchor-id="training-and-testing">Training and Testing</h3>
<p>We have two datasets: - 2022 NFL games dataset which is our training dataset - 2023 NFL games dataset which is our testing dataset</p>
<p>The model is trained on the training set (2022 NFL games) and will be evaluated on the testing set (2023 NFL games) to evaluate its accuracy.</p>
</section>
<section id="hyperparameter-tuning" class="level3">
<h3 class="anchored" data-anchor-id="hyperparameter-tuning">Hyperparameter Tuning</h3>
<p>To improve model performance, hyperparameters were tuned on the training set using 5-fold CV with random search. The following hyperparameters samples were considered: - Random Forest: - max_features: features per split (‘sqrt’, 1/3, 0.5) - min_samples_leaf: minimum samples or observation in each leaf (1, 5, 10)<br>
- n_estimators: number of trees (set to 200)</p>
<ul>
<li>XGBoost:
<ul>
<li>max_depth: depth of each tree (4,6,8)</li>
<li>learning_rate: shrinkage per step (0.05, 0.1, 0.5)<br>
</li>
<li>reg_lambda: L2 regularization (0.1, 1, 10)</li>
<li>reg_alpha: L1 regularization (0, 0.1, 1)</li>
<li>n_estimators: number of trees (set to 200)</li>
</ul></li>
</ul>
<p>Here are the best hyperaparmeter combinations found for each model: - Random Forest: - max_features: ‘sqrt’ - min_samples_leaf: 10 - n_estimators: 200</p>
<ul>
<li>XGBoost:
<ul>
<li>max_depth: 6</li>
<li>learning_rate: 0.05</li>
<li>reg_lambda: 1</li>
<li>reg_alpha: 0.1</li>
<li>n_estimators: 200</li>
</ul></li>
</ul>
<div id="4c48b2c4" class="cell" data-execution_count="26">
<div class="cell-output cell-output-stderr">
<pre><code>C:\Users\shnta\Desktop\JSC370_2026_Winter\.venv\Lib\site-packages\sklearn\model_selection\_search.py:324: UserWarning: The total space of parameters 9 is smaller than n_iter=10. Running 9 iterations. For exhaustive searches, use GridSearchCV.</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="26">
<style>#sk-container-id-1 {
  /* Definition of color scheme common for light and dark mode */
  --sklearn-color-text: #000;
  --sklearn-color-text-muted: #666;
  --sklearn-color-line: gray;
  /* Definition of color scheme for unfitted estimators */
  --sklearn-color-unfitted-level-0: #fff5e6;
  --sklearn-color-unfitted-level-1: #f6e4d2;
  --sklearn-color-unfitted-level-2: #ffe0b3;
  --sklearn-color-unfitted-level-3: chocolate;
  /* Definition of color scheme for fitted estimators */
  --sklearn-color-fitted-level-0: #f0f8ff;
  --sklearn-color-fitted-level-1: #d4ebff;
  --sklearn-color-fitted-level-2: #b3dbfd;
  --sklearn-color-fitted-level-3: cornflowerblue;
}

#sk-container-id-1.light {
  /* Specific color for light theme */
  --sklearn-color-text-on-default-background: black;
  --sklearn-color-background: white;
  --sklearn-color-border-box: black;
  --sklearn-color-icon: #696969;
}

#sk-container-id-1.dark {
  --sklearn-color-text-on-default-background: white;
  --sklearn-color-background: #111;
  --sklearn-color-border-box: white;
  --sklearn-color-icon: #878787;
}

#sk-container-id-1 {
  color: var(--sklearn-color-text);
}

#sk-container-id-1 pre {
  padding: 0;
}

#sk-container-id-1 input.sk-hidden--visually {
  border: 0;
  clip: rect(1px 1px 1px 1px);
  clip: rect(1px, 1px, 1px, 1px);
  height: 1px;
  margin: -1px;
  overflow: hidden;
  padding: 0;
  position: absolute;
  width: 1px;
}

#sk-container-id-1 div.sk-dashed-wrapped {
  border: 1px dashed var(--sklearn-color-line);
  margin: 0 0.4em 0.5em 0.4em;
  box-sizing: border-box;
  padding-bottom: 0.4em;
  background-color: var(--sklearn-color-background);
}

#sk-container-id-1 div.sk-container {
  /* jupyter's `normalize.less` sets `[hidden] { display: none; }`
     but bootstrap.min.css set `[hidden] { display: none !important; }`
     so we also need the `!important` here to be able to override the
     default hidden behavior on the sphinx rendered scikit-learn.org.
     See: https://github.com/scikit-learn/scikit-learn/issues/21755 */
  display: inline-block !important;
  position: relative;
}

#sk-container-id-1 div.sk-text-repr-fallback {
  display: none;
}

div.sk-parallel-item,
div.sk-serial,
div.sk-item {
  /* draw centered vertical line to link estimators */
  background-image: linear-gradient(var(--sklearn-color-text-on-default-background), var(--sklearn-color-text-on-default-background));
  background-size: 2px 100%;
  background-repeat: no-repeat;
  background-position: center center;
}

/* Parallel-specific style estimator block */

#sk-container-id-1 div.sk-parallel-item::after {
  content: "";
  width: 100%;
  border-bottom: 2px solid var(--sklearn-color-text-on-default-background);
  flex-grow: 1;
}

#sk-container-id-1 div.sk-parallel {
  display: flex;
  align-items: stretch;
  justify-content: center;
  background-color: var(--sklearn-color-background);
  position: relative;
}

#sk-container-id-1 div.sk-parallel-item {
  display: flex;
  flex-direction: column;
}

#sk-container-id-1 div.sk-parallel-item:first-child::after {
  align-self: flex-end;
  width: 50%;
}

#sk-container-id-1 div.sk-parallel-item:last-child::after {
  align-self: flex-start;
  width: 50%;
}

#sk-container-id-1 div.sk-parallel-item:only-child::after {
  width: 0;
}

/* Serial-specific style estimator block */

#sk-container-id-1 div.sk-serial {
  display: flex;
  flex-direction: column;
  align-items: center;
  background-color: var(--sklearn-color-background);
  padding-right: 1em;
  padding-left: 1em;
}


/* Toggleable style: style used for estimator/Pipeline/ColumnTransformer box that is
clickable and can be expanded/collapsed.
- Pipeline and ColumnTransformer use this feature and define the default style
- Estimators will overwrite some part of the style using the `sk-estimator` class
*/

/* Pipeline and ColumnTransformer style (default) */

#sk-container-id-1 div.sk-toggleable {
  /* Default theme specific background. It is overwritten whether we have a
  specific estimator or a Pipeline/ColumnTransformer */
  background-color: var(--sklearn-color-background);
}

/* Toggleable label */
#sk-container-id-1 label.sk-toggleable__label {
  cursor: pointer;
  display: flex;
  width: 100%;
  margin-bottom: 0;
  padding: 0.5em;
  box-sizing: border-box;
  text-align: center;
  align-items: center;
  justify-content: center;
  gap: 0.5em;
}

#sk-container-id-1 label.sk-toggleable__label .caption {
  font-size: 0.6rem;
  font-weight: lighter;
  color: var(--sklearn-color-text-muted);
}

#sk-container-id-1 label.sk-toggleable__label-arrow:before {
  /* Arrow on the left of the label */
  content: "▸";
  float: left;
  margin-right: 0.25em;
  color: var(--sklearn-color-icon);
}

#sk-container-id-1 label.sk-toggleable__label-arrow:hover:before {
  color: var(--sklearn-color-text);
}

/* Toggleable content - dropdown */

#sk-container-id-1 div.sk-toggleable__content {
  display: none;
  text-align: left;
  /* unfitted */
  background-color: var(--sklearn-color-unfitted-level-0);
}

#sk-container-id-1 div.sk-toggleable__content.fitted {
  /* fitted */
  background-color: var(--sklearn-color-fitted-level-0);
}

#sk-container-id-1 div.sk-toggleable__content pre {
  margin: 0.2em;
  border-radius: 0.25em;
  color: var(--sklearn-color-text);
  /* unfitted */
  background-color: var(--sklearn-color-unfitted-level-0);
}

#sk-container-id-1 div.sk-toggleable__content.fitted pre {
  /* unfitted */
  background-color: var(--sklearn-color-fitted-level-0);
}

#sk-container-id-1 input.sk-toggleable__control:checked~div.sk-toggleable__content {
  /* Expand drop-down */
  display: block;
  width: 100%;
  overflow: visible;
}

#sk-container-id-1 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {
  content: "▾";
}

/* Pipeline/ColumnTransformer-specific style */

#sk-container-id-1 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {
  color: var(--sklearn-color-text);
  background-color: var(--sklearn-color-unfitted-level-2);
}

#sk-container-id-1 div.sk-label.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {
  background-color: var(--sklearn-color-fitted-level-2);
}

/* Estimator-specific style */

/* Colorize estimator box */
#sk-container-id-1 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {
  /* unfitted */
  background-color: var(--sklearn-color-unfitted-level-2);
}

#sk-container-id-1 div.sk-estimator.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {
  /* fitted */
  background-color: var(--sklearn-color-fitted-level-2);
}

#sk-container-id-1 div.sk-label label.sk-toggleable__label,
#sk-container-id-1 div.sk-label label {
  /* The background is the default theme color */
  color: var(--sklearn-color-text-on-default-background);
}

/* On hover, darken the color of the background */
#sk-container-id-1 div.sk-label:hover label.sk-toggleable__label {
  color: var(--sklearn-color-text);
  background-color: var(--sklearn-color-unfitted-level-2);
}

/* Label box, darken color on hover, fitted */
#sk-container-id-1 div.sk-label.fitted:hover label.sk-toggleable__label.fitted {
  color: var(--sklearn-color-text);
  background-color: var(--sklearn-color-fitted-level-2);
}

/* Estimator label */

#sk-container-id-1 div.sk-label label {
  font-family: monospace;
  font-weight: bold;
  line-height: 1.2em;
}

#sk-container-id-1 div.sk-label-container {
  text-align: center;
}

/* Estimator-specific */
#sk-container-id-1 div.sk-estimator {
  font-family: monospace;
  border: 1px dotted var(--sklearn-color-border-box);
  border-radius: 0.25em;
  box-sizing: border-box;
  margin-bottom: 0.5em;
  /* unfitted */
  background-color: var(--sklearn-color-unfitted-level-0);
}

#sk-container-id-1 div.sk-estimator.fitted {
  /* fitted */
  background-color: var(--sklearn-color-fitted-level-0);
}

/* on hover */
#sk-container-id-1 div.sk-estimator:hover {
  /* unfitted */
  background-color: var(--sklearn-color-unfitted-level-2);
}

#sk-container-id-1 div.sk-estimator.fitted:hover {
  /* fitted */
  background-color: var(--sklearn-color-fitted-level-2);
}

/* Specification for estimator info (e.g. "i" and "?") */

/* Common style for "i" and "?" */

.sk-estimator-doc-link,
a:link.sk-estimator-doc-link,
a:visited.sk-estimator-doc-link {
  float: right;
  font-size: smaller;
  line-height: 1em;
  font-family: monospace;
  background-color: var(--sklearn-color-unfitted-level-0);
  border-radius: 1em;
  height: 1em;
  width: 1em;
  text-decoration: none !important;
  margin-left: 0.5em;
  text-align: center;
  /* unfitted */
  border: var(--sklearn-color-unfitted-level-3) 1pt solid;
  color: var(--sklearn-color-unfitted-level-3);
}

.sk-estimator-doc-link.fitted,
a:link.sk-estimator-doc-link.fitted,
a:visited.sk-estimator-doc-link.fitted {
  /* fitted */
  background-color: var(--sklearn-color-fitted-level-0);
  border: var(--sklearn-color-fitted-level-3) 1pt solid;
  color: var(--sklearn-color-fitted-level-3);
}

/* On hover */
div.sk-estimator:hover .sk-estimator-doc-link:hover,
.sk-estimator-doc-link:hover,
div.sk-label-container:hover .sk-estimator-doc-link:hover,
.sk-estimator-doc-link:hover {
  /* unfitted */
  background-color: var(--sklearn-color-unfitted-level-3);
  border: var(--sklearn-color-fitted-level-0) 1pt solid;
  color: var(--sklearn-color-unfitted-level-0);
  text-decoration: none;
}

div.sk-estimator.fitted:hover .sk-estimator-doc-link.fitted:hover,
.sk-estimator-doc-link.fitted:hover,
div.sk-label-container:hover .sk-estimator-doc-link.fitted:hover,
.sk-estimator-doc-link.fitted:hover {
  /* fitted */
  background-color: var(--sklearn-color-fitted-level-3);
  border: var(--sklearn-color-fitted-level-0) 1pt solid;
  color: var(--sklearn-color-fitted-level-0);
  text-decoration: none;
}

/* Span, style for the box shown on hovering the info icon */
.sk-estimator-doc-link span {
  display: none;
  z-index: 9999;
  position: relative;
  font-weight: normal;
  right: .2ex;
  padding: .5ex;
  margin: .5ex;
  width: min-content;
  min-width: 20ex;
  max-width: 50ex;
  color: var(--sklearn-color-text);
  box-shadow: 2pt 2pt 4pt #999;
  /* unfitted */
  background: var(--sklearn-color-unfitted-level-0);
  border: .5pt solid var(--sklearn-color-unfitted-level-3);
}

.sk-estimator-doc-link.fitted span {
  /* fitted */
  background: var(--sklearn-color-fitted-level-0);
  border: var(--sklearn-color-fitted-level-3);
}

.sk-estimator-doc-link:hover span {
  display: block;
}

/* "?"-specific style due to the `<a>` HTML tag */

#sk-container-id-1 a.estimator_doc_link {
  float: right;
  font-size: 1rem;
  line-height: 1em;
  font-family: monospace;
  background-color: var(--sklearn-color-unfitted-level-0);
  border-radius: 1rem;
  height: 1rem;
  width: 1rem;
  text-decoration: none;
  /* unfitted */
  color: var(--sklearn-color-unfitted-level-1);
  border: var(--sklearn-color-unfitted-level-1) 1pt solid;
}

#sk-container-id-1 a.estimator_doc_link.fitted {
  /* fitted */
  background-color: var(--sklearn-color-fitted-level-0);
  border: var(--sklearn-color-fitted-level-1) 1pt solid;
  color: var(--sklearn-color-fitted-level-1);
}

/* On hover */
#sk-container-id-1 a.estimator_doc_link:hover {
  /* unfitted */
  background-color: var(--sklearn-color-unfitted-level-3);
  color: var(--sklearn-color-background);
  text-decoration: none;
}

#sk-container-id-1 a.estimator_doc_link.fitted:hover {
  /* fitted */
  background-color: var(--sklearn-color-fitted-level-3);
}

.estimator-table {
    font-family: monospace;
}

.estimator-table summary {
    padding: .5rem;
    cursor: pointer;
}

.estimator-table summary::marker {
    font-size: 0.7rem;
}

.estimator-table details[open] {
    padding-left: 0.1rem;
    padding-right: 0.1rem;
    padding-bottom: 0.3rem;
}

.estimator-table .parameters-table {
    margin-left: auto !important;
    margin-right: auto !important;
    margin-top: 0;
}

.estimator-table .parameters-table tr:nth-child(odd) {
    background-color: #fff;
}

.estimator-table .parameters-table tr:nth-child(even) {
    background-color: #f6f6f6;
}

.estimator-table .parameters-table tr:hover {
    background-color: #e0e0e0;
}

.estimator-table table td {
    border: 1px solid rgba(106, 105, 104, 0.232);
}

/*
    `table td`is set in notebook with right text-align.
    We need to overwrite it.
*/
.estimator-table table td.param {
    text-align: left;
    position: relative;
    padding: 0;
}

.user-set td {
    color:rgb(255, 94, 0);
    text-align: left !important;
}

.user-set td.value {
    color:rgb(255, 94, 0);
    background-color: transparent;
}

.default td {
    color: black;
    text-align: left !important;
}

.user-set td i,
.default td i {
    color: black;
}

/*
    Styles for parameter documentation links
    We need styling for visited so jupyter doesn't overwrite it
*/
a.param-doc-link,
a.param-doc-link:link,
a.param-doc-link:visited {
    text-decoration: underline dashed;
    text-underline-offset: .3em;
    color: inherit;
    display: block;
    padding: .5em;
}

/* "hack" to make the entire area of the cell containing the link clickable */
a.param-doc-link::before {
    position: absolute;
    content: "";
    inset: 0;
}

.param-doc-description {
    display: none;
    position: absolute;
    z-index: 9999;
    left: 0;
    padding: .5ex;
    margin-left: 1.5em;
    color: var(--sklearn-color-text);
    box-shadow: .3em .3em .4em #999;
    width: max-content;
    text-align: left;
    max-height: 10em;
    overflow-y: auto;

    /* unfitted */
    background: var(--sklearn-color-unfitted-level-0);
    border: thin solid var(--sklearn-color-unfitted-level-3);
}

/* Fitted state for parameter tooltips */
.fitted .param-doc-description {
    /* fitted */
    background: var(--sklearn-color-fitted-level-0);
    border: thin solid var(--sklearn-color-fitted-level-3);
}

.param-doc-link:hover .param-doc-description {
    display: block;
}

.copy-paste-icon {
    background-image: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48IS0tIUZvbnQgQXdlc29tZSBGcmVlIDYuNy4yIGJ5IEBmb250YXdlc29tZSAtIGh0dHBzOi8vZm9udGF3ZXNvbWUuY29tIExpY2Vuc2UgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbS9saWNlbnNlL2ZyZWUgQ29weXJpZ2h0IDIwMjUgRm9udGljb25zLCBJbmMuLS0+PHBhdGggZD0iTTIwOCAwTDMzMi4xIDBjMTIuNyAwIDI0LjkgNS4xIDMzLjkgMTQuMWw2Ny45IDY3LjljOSA5IDE0LjEgMjEuMiAxNC4xIDMzLjlMNDQ4IDMzNmMwIDI2LjUtMjEuNSA0OC00OCA0OGwtMTkyIDBjLTI2LjUgMC00OC0yMS41LTQ4LTQ4bDAtMjg4YzAtMjYuNSAyMS41LTQ4IDQ4LTQ4ek00OCAxMjhsODAgMCAwIDY0LTY0IDAgMCAyNTYgMTkyIDAgMC0zMiA2NCAwIDAgNDhjMCAyNi41LTIxLjUgNDgtNDggNDhMNDggNTEyYy0yNi41IDAtNDgtMjEuNS00OC00OEwwIDE3NmMwLTI2LjUgMjEuNS00OCA0OC00OHoiLz48L3N2Zz4=);
    background-repeat: no-repeat;
    background-size: 14px 14px;
    background-position: 0;
    display: inline-block;
    width: 14px;
    height: 14px;
    cursor: pointer;
}
</style><div id="sk-container-id-1" class="sk-top-container"><div class="sk-text-repr-fallback"><pre>RandomizedSearchCV(cv=5,
                   estimator=RandomForestClassifier(n_estimators=200, n_jobs=1,
                                                    random_state=65),
                   n_jobs=1,
                   param_distributions={'max_features': ['sqrt',
                                                         0.3333333333333333,
                                                         0.5],
                                        'min_samples_leaf': [1, 5, 10]},
                   scoring='roc_auc')</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br>On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class="sk-container" hidden=""><div class="sk-item sk-dashed-wrapped"><div class="sk-label-container"><div class="sk-label fitted sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-1" type="checkbox"><label for="sk-estimator-id-1" class="sk-toggleable__label fitted sk-toggleable__label-arrow"><div><div>RandomizedSearchCV</div></div><div><a class="sk-estimator-doc-link fitted" rel="noreferrer" target="_blank" href="https://scikit-learn.org/1.8/modules/generated/sklearn.model_selection.RandomizedSearchCV.html">?<span>Documentation for RandomizedSearchCV</span></a><span class="sk-estimator-doc-link fitted">i<span>Fitted</span></span></div></label><div class="sk-toggleable__content fitted" data-param-prefix="">
        <div class="estimator-table">
            <details>
                <summary>Parameters</summary>
                
<table class="parameters-table caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<tbody>
<tr class="user-set odd">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.model_selection.RandomizedSearchCV.html#:~:text=estimator,-estimator%20object" class="param-doc-link" rel="noreferrer" target="_blank">estimator <span class="param-doc-description">estimator: estimator object<br>
<br>
An object of that type is instantiated for each grid point.<br>
This is assumed to implement the scikit-learn estimator interface.<br>
Either estimator needs to provide a ``score`` function,<br>
or ``scoring`` must be passed.</span></a></td>
<td class="value">RandomForestC...ndom_state=65)</td>
</tr>
<tr class="user-set even">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.model_selection.RandomizedSearchCV.html#:~:text=param_distributions,-dict%20or%20list%20of%20dicts" class="param-doc-link" rel="noreferrer" target="_blank">param_distributions <span class="param-doc-description">param_distributions: dict or list of dicts<br>
<br>
Dictionary with parameters names (`str`) as keys and distributions<br>
or lists of parameters to try. Distributions must provide a ``rvs``<br>
method for sampling (such as those from scipy.stats.distributions).<br>
If a list is given, it is sampled uniformly.<br>
If a list of dicts is given, first a dict is sampled uniformly, and<br>
then a parameter is sampled using that dict as above.</span></a></td>
<td class="value">{'max_features': ['sqrt', 0.3333333333333333, ...], 'min_samples_leaf': [1, 5, ...]}</td>
</tr>
<tr class="default odd">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.model_selection.RandomizedSearchCV.html#:~:text=n_iter,-int%2C%20default%3D10" class="param-doc-link" rel="noreferrer" target="_blank">n_iter <span class="param-doc-description">n_iter: int, default=10<br>
<br>
Number of parameter settings that are sampled. n_iter trades<br>
off runtime vs quality of the solution.</span></a></td>
<td class="value">10</td>
</tr>
<tr class="user-set even">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.model_selection.RandomizedSearchCV.html#:~:text=scoring,-str%2C%20callable%2C%20list%2C%20tuple%20or%20dict%2C%20default%3DNone" class="param-doc-link" rel="noreferrer" target="_blank">scoring <span class="param-doc-description">scoring: str, callable, list, tuple or dict, default=None<br>
<br>
Strategy to evaluate the performance of the cross-validated model on<br>
the test set.<br>
<br>
If `scoring` represents a single score, one can use:<br>
<br>
- a single string (see :ref:`scoring_string_names`);<br>
- a callable (see :ref:`scoring_callable`) that returns a single value;<br>
- `None`, the `estimator`'s<br>
:ref:`default evaluation criterion <scoring_api_overview>` is used.<br>
<br>
If `scoring` represents multiple scores, one can use:<br>
<br>
- a list or tuple of unique strings;<br>
- a callable returning a dictionary where the keys are the metric<br>
names and the values are the metric scores;<br>
- a dictionary with metric names as keys and callables as values.<br>
<br>
See :ref:`multimetric_grid_search` for an example.<br>
<br>
If None, the estimator's score method is used.</scoring_api_overview></span></a></td>
<td class="value">'roc_auc'</td>
</tr>
<tr class="user-set odd">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.model_selection.RandomizedSearchCV.html#:~:text=n_jobs,-int%2C%20default%3DNone" class="param-doc-link" rel="noreferrer" target="_blank">n_jobs <span class="param-doc-description">n_jobs: int, default=None<br>
<br>
Number of jobs to run in parallel.<br>
``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.<br>
``-1`` means using all processors. See :term:`Glossary <n_jobs>`<br>
for more details.<br>
<br>
.. versionchanged:: v0.20<br>
`n_jobs` default changed from 1 to None</n_jobs></span></a></td>
<td class="value">1</td>
</tr>
<tr class="default even">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.model_selection.RandomizedSearchCV.html#:~:text=refit,-bool%2C%20str%2C%20or%20callable%2C%20default%3DTrue" class="param-doc-link" rel="noreferrer" target="_blank">refit <span class="param-doc-description">refit: bool, str, or callable, default=True<br>
<br>
Refit an estimator using the best found parameters on the whole<br>
dataset.<br>
<br>
For multiple metric evaluation, this needs to be a `str` denoting the<br>
scorer that would be used to find the best parameters for refitting<br>
the estimator at the end.<br>
<br>
Where there are considerations other than maximum score in<br>
choosing a best estimator, ``refit`` can be set to a function which<br>
returns the selected ``best_index_`` given the ``cv_results_``. In that<br>
case, the ``best_estimator_`` and ``best_params_`` will be set<br>
according to the returned ``best_index_`` while the ``best_score_``<br>
attribute will not be available.<br>
<br>
The refitted estimator is made available at the ``best_estimator_``<br>
attribute and permits using ``predict`` directly on this<br>
``RandomizedSearchCV`` instance.<br>
<br>
Also for multiple metric evaluation, the attributes ``best_index_``,<br>
``best_score_`` and ``best_params_`` will only be available if<br>
``refit`` is set and all of them will be determined w.r.t this specific<br>
scorer.<br>
<br>
See ``scoring`` parameter to know more about multiple metric<br>
evaluation.<br>
<br>
See :ref:`this example<br>
<sphx_glr_auto_examples_model_selection_plot_grid_search_refit_callable.py>`<br>
for an example of how to use ``refit=callable`` to balance model<br>
complexity and cross-validated score.<br>
<br>
.. versionchanged:: 0.20<br>
Support for callable added.</sphx_glr_auto_examples_model_selection_plot_grid_search_refit_callable.py></span></a></td>
<td class="value">True</td>
</tr>
<tr class="user-set odd">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.model_selection.RandomizedSearchCV.html#:~:text=cv,-int%2C%20cross-validation%20generator%20or%20an%20iterable%2C%20default%3DNone" class="param-doc-link" rel="noreferrer" target="_blank">cv <span class="param-doc-description">cv: int, cross-validation generator or an iterable, default=None<br>
<br>
Determines the cross-validation splitting strategy.<br>
Possible inputs for cv are:<br>
<br>
- None, to use the default 5-fold cross validation,<br>
- integer, to specify the number of folds in a `(Stratified)KFold`,<br>
- :term:`CV splitter`,<br>
- An iterable yielding (train, test) splits as arrays of indices.<br>
<br>
For integer/None inputs, if the estimator is a classifier and ``y`` is<br>
either binary or multiclass, :class:`StratifiedKFold` is used. In all<br>
other cases, :class:`KFold` is used. These splitters are instantiated<br>
with `shuffle=False` so the splits will be the same across calls.<br>
<br>
Refer :ref:`User Guide <cross_validation>` for the various<br>
cross-validation strategies that can be used here.<br>
<br>
.. versionchanged:: 0.22<br>
``cv`` default value if None changed from 3-fold to 5-fold.</cross_validation></span></a></td>
<td class="value">5</td>
</tr>
<tr class="default even">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.model_selection.RandomizedSearchCV.html#:~:text=verbose,-int" class="param-doc-link" rel="noreferrer" target="_blank">verbose <span class="param-doc-description">verbose: int<br>
<br>
Controls the verbosity: the higher, the more messages.<br>
<br>
- &gt;1 : the computation time for each fold and parameter candidate is<br>
displayed;<br>
- &gt;2 : the score is also displayed;<br>
- &gt;3 : the fold and candidate parameter indexes are also displayed<br>
together with the starting time of the computation.</span></a></td>
<td class="value">0</td>
</tr>
<tr class="default odd">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.model_selection.RandomizedSearchCV.html#:~:text=pre_dispatch,-int%2C%20or%20str%2C%20default%3D%272%2An_jobs%27" class="param-doc-link" rel="noreferrer" target="_blank">pre_dispatch <span class="param-doc-description">pre_dispatch: int, or str, default='2*n_jobs'<br>
<br>
Controls the number of jobs that get dispatched during parallel<br>
execution. Reducing this number can be useful to avoid an<br>
explosion of memory consumption when more jobs get dispatched<br>
than CPUs can process. This parameter can be:<br>
<br>
- None, in which case all the jobs are immediately created and spawned. Use<br>
this for lightweight and fast-running jobs, to avoid delays due to on-demand<br>
spawning of the jobs<br>
- An int, giving the exact number of total jobs that are spawned<br>
- A str, giving an expression as a function of n_jobs, as in '2*n_jobs'</span></a></td>
<td class="value">'2*n_jobs'</td>
</tr>
<tr class="default even">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.model_selection.RandomizedSearchCV.html#:~:text=random_state,-int%2C%20RandomState%20instance%20or%20None%2C%20default%3DNone" class="param-doc-link" rel="noreferrer" target="_blank">random_state <span class="param-doc-description">random_state: int, RandomState instance or None, default=None<br>
<br>
Pseudo random number generator state used for random uniform sampling<br>
from lists of possible values instead of scipy.stats distributions.<br>
Pass an int for reproducible output across multiple<br>
function calls.<br>
See :term:`Glossary <random_state>`.</random_state></span></a></td>
<td class="value">None</td>
</tr>
<tr class="default odd">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.model_selection.RandomizedSearchCV.html#:~:text=error_score,-%27raise%27%20or%20numeric%2C%20default%3Dnp.nan" class="param-doc-link" rel="noreferrer" target="_blank">error_score <span class="param-doc-description">error_score: 'raise' or numeric, default=np.nan<br>
<br>
Value to assign to the score if an error occurs in estimator fitting.<br>
If set to 'raise', the error is raised. If a numeric value is given,<br>
FitFailedWarning is raised. This parameter does not affect the refit<br>
step, which will always raise the error.</span></a></td>
<td class="value">nan</td>
</tr>
<tr class="default even">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.model_selection.RandomizedSearchCV.html#:~:text=return_train_score,-bool%2C%20default%3DFalse" class="param-doc-link" rel="noreferrer" target="_blank">return_train_score <span class="param-doc-description">return_train_score: bool, default=False<br>
<br>
If ``False``, the ``cv_results_`` attribute will not include training<br>
scores.<br>
Computing training scores is used to get insights on how different<br>
parameter settings impact the overfitting/underfitting trade-off.<br>
However computing the scores on the training set can be computationally<br>
expensive and is not strictly required to select the parameters that<br>
yield the best generalization performance.<br>
<br>
.. versionadded:: 0.19<br>
<br>
.. versionchanged:: 0.21<br>
Default value was changed from ``True`` to ``False``</span></a></td>
<td class="value">False</td>
</tr>
</tbody>
</table>

            </details>
        </div>
    </div></div></div><div class="sk-parallel"><div class="sk-parallel-item"><div class="sk-item"><div class="sk-label-container"><div class="sk-label fitted sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-2" type="checkbox"><label for="sk-estimator-id-2" class="sk-toggleable__label fitted sk-toggleable__label-arrow"><div><div>best_estimator_: RandomForestClassifier</div></div></label><div class="sk-toggleable__content fitted" data-param-prefix="best_estimator___"><pre>RandomForestClassifier(min_samples_leaf=10, n_estimators=200, n_jobs=1,
                       random_state=65)</pre></div></div></div><div class="sk-serial"><div class="sk-item"><div class="sk-estimator fitted sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-3" type="checkbox"><label for="sk-estimator-id-3" class="sk-toggleable__label fitted sk-toggleable__label-arrow"><div><div>RandomForestClassifier</div></div><div><a class="sk-estimator-doc-link fitted" rel="noreferrer" target="_blank" href="https://scikit-learn.org/1.8/modules/generated/sklearn.ensemble.RandomForestClassifier.html">?<span>Documentation for RandomForestClassifier</span></a></div></label><div class="sk-toggleable__content fitted" data-param-prefix="best_estimator___">
        <div class="estimator-table">
            <details>
                <summary>Parameters</summary>
                
<table class="parameters-table caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<tbody>
<tr class="user-set odd">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.ensemble.RandomForestClassifier.html#:~:text=n_estimators,-int%2C%20default%3D100" class="param-doc-link" rel="noreferrer" target="_blank">n_estimators <span class="param-doc-description">n_estimators: int, default=100<br>
<br>
The number of trees in the forest.<br>
<br>
.. versionchanged:: 0.22<br>
The default value of ``n_estimators`` changed from 10 to 100<br>
in 0.22.</span></a></td>
<td class="value">200</td>
</tr>
<tr class="default even">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.ensemble.RandomForestClassifier.html#:~:text=criterion,-%7B%22gini%22%2C%20%22entropy%22%2C%20%22log_loss%22%7D%2C%20default%3D%22gini%22" class="param-doc-link" rel="noreferrer" target="_blank">criterion <span class="param-doc-description">criterion: {"gini", "entropy", "log_loss"}, default="gini"<br>
<br>
The function to measure the quality of a split. Supported criteria are<br>
"gini" for the Gini impurity and "log_loss" and "entropy" both for the<br>
Shannon information gain, see :ref:`tree_mathematical_formulation`.<br>
Note: This parameter is tree-specific.</span></a></td>
<td class="value">'gini'</td>
</tr>
<tr class="default odd">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.ensemble.RandomForestClassifier.html#:~:text=max_depth,-int%2C%20default%3DNone" class="param-doc-link" rel="noreferrer" target="_blank">max_depth <span class="param-doc-description">max_depth: int, default=None<br>
<br>
The maximum depth of the tree. If None, then nodes are expanded until<br>
all leaves are pure or until all leaves contain less than<br>
min_samples_split samples.</span></a></td>
<td class="value">None</td>
</tr>
<tr class="default even">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.ensemble.RandomForestClassifier.html#:~:text=min_samples_split,-int%20or%20float%2C%20default%3D2" class="param-doc-link" rel="noreferrer" target="_blank">min_samples_split <span class="param-doc-description">min_samples_split: int or float, default=2<br>
<br>
The minimum number of samples required to split an internal node:<br>
<br>
- If int, then consider `min_samples_split` as the minimum number.<br>
- If float, then `min_samples_split` is a fraction and<br>
`ceil(min_samples_split * n_samples)` are the minimum<br>
number of samples for each split.<br>
<br>
.. versionchanged:: 0.18<br>
Added float values for fractions.</span></a></td>
<td class="value">2</td>
</tr>
<tr class="user-set odd">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.ensemble.RandomForestClassifier.html#:~:text=min_samples_leaf,-int%20or%20float%2C%20default%3D1" class="param-doc-link" rel="noreferrer" target="_blank">min_samples_leaf <span class="param-doc-description">min_samples_leaf: int or float, default=1<br>
<br>
The minimum number of samples required to be at a leaf node.<br>
A split point at any depth will only be considered if it leaves at<br>
least ``min_samples_leaf`` training samples in each of the left and<br>
right branches. This may have the effect of smoothing the model,<br>
especially in regression.<br>
<br>
- If int, then consider `min_samples_leaf` as the minimum number.<br>
- If float, then `min_samples_leaf` is a fraction and<br>
`ceil(min_samples_leaf * n_samples)` are the minimum<br>
number of samples for each node.<br>
<br>
.. versionchanged:: 0.18<br>
Added float values for fractions.</span></a></td>
<td class="value">10</td>
</tr>
<tr class="default even">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.ensemble.RandomForestClassifier.html#:~:text=min_weight_fraction_leaf,-float%2C%20default%3D0.0" class="param-doc-link" rel="noreferrer" target="_blank">min_weight_fraction_leaf <span class="param-doc-description">min_weight_fraction_leaf: float, default=0.0<br>
<br>
The minimum weighted fraction of the sum total of weights (of all<br>
the input samples) required to be at a leaf node. Samples have<br>
equal weight when sample_weight is not provided.</span></a></td>
<td class="value">0.0</td>
</tr>
<tr class="default odd">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.ensemble.RandomForestClassifier.html#:~:text=max_features,-%7B%22sqrt%22%2C%20%22log2%22%2C%20None%7D%2C%20int%20or%20float%2C%20default%3D%22sqrt%22" class="param-doc-link" rel="noreferrer" target="_blank">max_features <span class="param-doc-description">max_features: {"sqrt", "log2", None}, int or float, default="sqrt"<br>
<br>
The number of features to consider when looking for the best split:<br>
<br>
- If int, then consider `max_features` features at each split.<br>
- If float, then `max_features` is a fraction and<br>
`max(1, int(max_features * n_features_in_))` features are considered at each<br>
split.<br>
- If "sqrt", then `max_features=sqrt(n_features)`.<br>
- If "log2", then `max_features=log2(n_features)`.<br>
- If None, then `max_features=n_features`.<br>
<br>
.. versionchanged:: 1.1<br>
The default of `max_features` changed from `"auto"` to `"sqrt"`.<br>
<br>
Note: the search for a split does not stop until at least one<br>
valid partition of the node samples is found, even if it requires to<br>
effectively inspect more than ``max_features`` features.</span></a></td>
<td class="value">'sqrt'</td>
</tr>
<tr class="default even">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.ensemble.RandomForestClassifier.html#:~:text=max_leaf_nodes,-int%2C%20default%3DNone" class="param-doc-link" rel="noreferrer" target="_blank">max_leaf_nodes <span class="param-doc-description">max_leaf_nodes: int, default=None<br>
<br>
Grow trees with ``max_leaf_nodes`` in best-first fashion.<br>
Best nodes are defined as relative reduction in impurity.<br>
If None then unlimited number of leaf nodes.</span></a></td>
<td class="value">None</td>
</tr>
<tr class="default odd">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.ensemble.RandomForestClassifier.html#:~:text=min_impurity_decrease,-float%2C%20default%3D0.0" class="param-doc-link" rel="noreferrer" target="_blank">min_impurity_decrease <span class="param-doc-description">min_impurity_decrease: float, default=0.0<br>
<br>
A node will be split if this split induces a decrease of the impurity<br>
greater than or equal to this value.<br>
<br>
The weighted impurity decrease equation is the following::<br>
<br>
N_t / N * (impurity - N_t_R / N_t * right_impurity<br>
- N_t_L / N_t * left_impurity)<br>
<br>
where ``N`` is the total number of samples, ``N_t`` is the number of<br>
samples at the current node, ``N_t_L`` is the number of samples in the<br>
left child, and ``N_t_R`` is the number of samples in the right child.<br>
<br>
``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,<br>
if ``sample_weight`` is passed.<br>
<br>
.. versionadded:: 0.19</span></a></td>
<td class="value">0.0</td>
</tr>
<tr class="default even">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.ensemble.RandomForestClassifier.html#:~:text=bootstrap,-bool%2C%20default%3DTrue" class="param-doc-link" rel="noreferrer" target="_blank">bootstrap <span class="param-doc-description">bootstrap: bool, default=True<br>
<br>
Whether bootstrap samples are used when building trees. If False, the<br>
whole dataset is used to build each tree.</span></a></td>
<td class="value">True</td>
</tr>
<tr class="default odd">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.ensemble.RandomForestClassifier.html#:~:text=oob_score,-bool%20or%20callable%2C%20default%3DFalse" class="param-doc-link" rel="noreferrer" target="_blank">oob_score <span class="param-doc-description">oob_score: bool or callable, default=False<br>
<br>
Whether to use out-of-bag samples to estimate the generalization score.<br>
By default, :func:`~sklearn.metrics.accuracy_score` is used.<br>
Provide a callable with signature `metric(y_true, y_pred)` to use a<br>
custom metric. Only available if `bootstrap=True`.<br>
<br>
For an illustration of out-of-bag (OOB) error estimation, see the example<br>
:ref:`sphx_glr_auto_examples_ensemble_plot_ensemble_oob.py`.</span></a></td>
<td class="value">False</td>
</tr>
<tr class="user-set even">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.ensemble.RandomForestClassifier.html#:~:text=n_jobs,-int%2C%20default%3DNone" class="param-doc-link" rel="noreferrer" target="_blank">n_jobs <span class="param-doc-description">n_jobs: int, default=None<br>
<br>
The number of jobs to run in parallel. :meth:`fit`, :meth:`predict`,<br>
:meth:`decision_path` and :meth:`apply` are all parallelized over the<br>
trees. ``None`` means 1 unless in a :obj:`joblib.parallel_backend`<br>
context. ``-1`` means using all processors. See :term:`Glossary<br>
<n_jobs>` for more details.</n_jobs></span></a></td>
<td class="value">1</td>
</tr>
<tr class="user-set odd">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.ensemble.RandomForestClassifier.html#:~:text=random_state,-int%2C%20RandomState%20instance%20or%20None%2C%20default%3DNone" class="param-doc-link" rel="noreferrer" target="_blank">random_state <span class="param-doc-description">random_state: int, RandomState instance or None, default=None<br>
<br>
Controls both the randomness of the bootstrapping of the samples used<br>
when building trees (if ``bootstrap=True``) and the sampling of the<br>
features to consider when looking for the best split at each node<br>
(if ``max_features &lt; n_features``).<br>
See :term:`Glossary <random_state>` for details.</random_state></span></a></td>
<td class="value">65</td>
</tr>
<tr class="default even">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.ensemble.RandomForestClassifier.html#:~:text=verbose,-int%2C%20default%3D0" class="param-doc-link" rel="noreferrer" target="_blank">verbose <span class="param-doc-description">verbose: int, default=0<br>
<br>
Controls the verbosity when fitting and predicting.</span></a></td>
<td class="value">0</td>
</tr>
<tr class="default odd">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.ensemble.RandomForestClassifier.html#:~:text=warm_start,-bool%2C%20default%3DFalse" class="param-doc-link" rel="noreferrer" target="_blank">warm_start <span class="param-doc-description">warm_start: bool, default=False<br>
<br>
When set to ``True``, reuse the solution of the previous call to fit<br>
and add more estimators to the ensemble, otherwise, just fit a whole<br>
new forest. See :term:`Glossary <warm_start>` and<br>
:ref:`tree_ensemble_warm_start` for details.</warm_start></span></a></td>
<td class="value">False</td>
</tr>
<tr class="default even">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.ensemble.RandomForestClassifier.html#:~:text=class_weight,-%7B%22balanced%22%2C%20%22balanced_subsample%22%7D%2C%20dict%20or%20list%20of%20dicts%2C%20%20%20%20%20%20%20%20%20%20%20%20%20default%3DNone" class="param-doc-link" rel="noreferrer" target="_blank">class_weight <span class="param-doc-description">class_weight: {"balanced", "balanced_subsample"}, dict or list of dicts, default=None<br>
<br>
Weights associated with classes in the form ``{class_label: weight}``.<br>
If not given, all classes are supposed to have weight one. For<br>
multi-output problems, a list of dicts can be provided in the same<br>
order as the columns of y.<br>
<br>
Note that for multioutput (including multilabel) weights should be<br>
defined for each class of every column in its own dict. For example,<br>
for four-class multilabel classification weights should be<br>
[{0: 1, 1: 1}, {0: 1, 1: 5}, {0: 1, 1: 1}, {0: 1, 1: 1}] instead of<br>
[{1:1}, {2:5}, {3:1}, {4:1}].<br>
<br>
The "balanced" mode uses the values of y to automatically adjust<br>
weights inversely proportional to class frequencies in the input data<br>
as ``n_samples / (n_classes * np.bincount(y))``<br>
<br>
The "balanced_subsample" mode is the same as "balanced" except that<br>
weights are computed based on the bootstrap sample for every tree<br>
grown.<br>
<br>
For multi-output, the weights of each column of y will be multiplied.<br>
<br>
Note that these weights will be multiplied with sample_weight (passed<br>
through the fit method) if sample_weight is specified.</span></a></td>
<td class="value">None</td>
</tr>
<tr class="default odd">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.ensemble.RandomForestClassifier.html#:~:text=ccp_alpha,-non-negative%20float%2C%20default%3D0.0" class="param-doc-link" rel="noreferrer" target="_blank">ccp_alpha <span class="param-doc-description">ccp_alpha: non-negative float, default=0.0<br>
<br>
Complexity parameter used for Minimal Cost-Complexity Pruning. The<br>
subtree with the largest cost complexity that is smaller than<br>
``ccp_alpha`` will be chosen. By default, no pruning is performed. See<br>
:ref:`minimal_cost_complexity_pruning` for details. See<br>
:ref:`sphx_glr_auto_examples_tree_plot_cost_complexity_pruning.py`<br>
for an example of such pruning.<br>
<br>
.. versionadded:: 0.22</span></a></td>
<td class="value">0.0</td>
</tr>
<tr class="default even">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.ensemble.RandomForestClassifier.html#:~:text=max_samples,-int%20or%20float%2C%20default%3DNone" class="param-doc-link" rel="noreferrer" target="_blank">max_samples <span class="param-doc-description">max_samples: int or float, default=None<br>
<br>
If bootstrap is True, the number of samples to draw from X<br>
to train each base estimator.<br>
<br>
- If None (default), then draw `X.shape[0]` samples.<br>
- If int, then draw `max_samples` samples.<br>
- If float, then draw `max(round(n_samples * max_samples), 1)` samples. Thus,<br>
`max_samples` should be in the interval `(0.0, 1.0]`.<br>
<br>
.. versionadded:: 0.22</span></a></td>
<td class="value">None</td>
</tr>
<tr class="default odd">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.ensemble.RandomForestClassifier.html#:~:text=monotonic_cst,-array-like%20of%20int%20of%20shape%20%28n_features%29%2C%20default%3DNone" class="param-doc-link" rel="noreferrer" target="_blank">monotonic_cst <span class="param-doc-description">monotonic_cst: array-like of int of shape (n_features), default=None<br>
<br>
Indicates the monotonicity constraint to enforce on each feature.<br>
- 1: monotonic increase<br>
- 0: no constraint<br>
- -1: monotonic decrease<br>
<br>
If monotonic_cst is None, no constraints are applied.<br>
<br>
Monotonicity constraints are not supported for:<br>
- multiclass classifications (i.e. when `n_classes &gt; 2`),<br>
- multioutput classifications (i.e. when `n_outputs_ &gt; 1`),<br>
- classifications trained on data with missing values.<br>
<br>
The constraints hold over the probability of the positive class.<br>
<br>
Read more in the :ref:`User Guide <monotonic_cst_gbdt>`.<br>
<br>
.. versionadded:: 1.4</monotonic_cst_gbdt></span></a></td>
<td class="value">None</td>
</tr>
</tbody>
</table>

            </details>
        </div>
    </div></div></div></div></div></div></div></div></div></div><script>function copyToClipboard(text, element) {
    // Get the parameter prefix from the closest toggleable content
    const toggleableContent = element.closest('.sk-toggleable__content');
    const paramPrefix = toggleableContent ? toggleableContent.dataset.paramPrefix : '';
    const fullParamName = paramPrefix ? `${paramPrefix}${text}` : text;

    const originalStyle = element.style;
    const computedStyle = window.getComputedStyle(element);
    const originalWidth = computedStyle.width;
    const originalHTML = element.innerHTML.replace('Copied!', '');

    navigator.clipboard.writeText(fullParamName)
        .then(() => {
            element.style.width = originalWidth;
            element.style.color = 'green';
            element.innerHTML = "Copied!";

            setTimeout(() => {
                element.innerHTML = originalHTML;
                element.style = originalStyle;
            }, 2000);
        })
        .catch(err => {
            console.error('Failed to copy:', err);
            element.style.color = 'red';
            element.innerHTML = "Failed!";
            setTimeout(() => {
                element.innerHTML = originalHTML;
                element.style = originalStyle;
            }, 2000);
        });
    return false;
}

document.querySelectorAll('.copy-paste-icon').forEach(function(element) {
    const toggleableContent = element.closest('.sk-toggleable__content');
    const paramPrefix = toggleableContent ? toggleableContent.dataset.paramPrefix : '';
    const paramName = element.parentElement.nextElementSibling
        .textContent.trim().split(' ')[0];
    const fullParamName = paramPrefix ? `${paramPrefix}${paramName}` : paramName;

    element.setAttribute('title', fullParamName);
});


/**
 * Adapted from Skrub
 * https://github.com/skrub-data/skrub/blob/403466d1d5d4dc76a7ef569b3f8228db59a31dc3/skrub/_reporting/_data/templates/report.js#L789
 * @returns "light" or "dark"
 */
function detectTheme(element) {
    const body = document.querySelector('body');

    // Check VSCode theme
    const themeKindAttr = body.getAttribute('data-vscode-theme-kind');
    const themeNameAttr = body.getAttribute('data-vscode-theme-name');

    if (themeKindAttr && themeNameAttr) {
        const themeKind = themeKindAttr.toLowerCase();
        const themeName = themeNameAttr.toLowerCase();

        if (themeKind.includes("dark") || themeName.includes("dark")) {
            return "dark";
        }
        if (themeKind.includes("light") || themeName.includes("light")) {
            return "light";
        }
    }

    // Check Jupyter theme
    if (body.getAttribute('data-jp-theme-light') === 'false') {
        return 'dark';
    } else if (body.getAttribute('data-jp-theme-light') === 'true') {
        return 'light';
    }

    // Guess based on a parent element's color
    const color = window.getComputedStyle(element.parentNode, null).getPropertyValue('color');
    const match = color.match(/^rgb\s*\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)\s*$/i);
    if (match) {
        const [r, g, b] = [
            parseFloat(match[1]),
            parseFloat(match[2]),
            parseFloat(match[3])
        ];

        // https://en.wikipedia.org/wiki/HSL_and_HSV#Lightness
        const luma = 0.299 * r + 0.587 * g + 0.114 * b;

        if (luma > 180) {
            // If the text is very bright we have a dark theme
            return 'dark';
        }
        if (luma < 75) {
            // If the text is very dark we have a light theme
            return 'light';
        }
        // Otherwise fall back to the next heuristic.
    }

    // Fallback to system preference
    return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
}


function forceTheme(elementId) {
    const estimatorElement = document.querySelector(`#${elementId}`);
    if (estimatorElement === null) {
        console.error(`Element with id ${elementId} not found.`);
    } else {
        const theme = detectTheme(estimatorElement);
        estimatorElement.classList.add(theme);
    }
}

forceTheme('sk-container-id-1');</script>
</div>
</div>
<div id="8162516b" class="cell" data-execution_count="27">
<div class="cell-output cell-output-stdout">
<pre><code>Fitting 5 folds for each of 10 candidates, totalling 50 fits</code></pre>
</div>
</div>
</section>
<section id="model-evaluation" class="level3">
<h3 class="anchored" data-anchor-id="model-evaluation">Model Evaluation</h3>
<p>After the models were rebuild with the best combinations of hyperparameter above and fit on the training data, the models were ran on the test data and their performance are evaluated using: - Accuracy: represents the model’s ability to predict wins correctly - F1-Score: represents the model’s ability to balance precision and recall - ROC-AUC: represents the model’s performance in distinguishing a win or loss across all thresholds</p>
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 20%">
<col style="width: 34%">
<col style="width: 14%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th>Test Accuracy</th>
<th>Misclassification Error</th>
<th>F1 Score</th>
<th>AUC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Random Forest</td>
<td>0.698</td>
<td>0.302</td>
<td>0.742</td>
<td>0.771</td>
</tr>
<tr class="even">
<td>XGBoost</td>
<td>0.693</td>
<td>0.307</td>
<td>0.739</td>
<td>0.758</td>
</tr>
</tbody>
</table>
<p><strong>Table 5: Model Performance Comparison</strong></p>
</section>
</section>
</section>
<section id="results" class="level1">
<h1>RESULTS</h1>
<div id="64092359" class="cell" data-execution_count="29">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_files/figure-html/cell-30-output-1.png" width="385" height="211" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Figure 5: Confusion Matrices of Models</strong> The Confusion Matrices shows diagonals shows the accuracy of both models. With greater proportion of the prediction (indicated by both the larger numbers and the darker shade of blue) lies at the true values (Predicted Win &amp; True Win, Predicted Loss &amp; True Loss). Notice that False Positives and False Negatives counts are significantly smaller than the True values, suggestsing the high accuracy in the both models.</p>
<div id="39480d9d" class="cell" data-execution_count="30">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Final_files/figure-html/cell-31-output-1.png" width="390" height="230" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Figure 6: Feature Importance Graphs of Models</strong> The Feature Importance Graphs highlights the top most influential features for each model. We see both models have score difference as the more dominant variable, followed by team strengths then remaining game time. This shows that not only does game statistics influence the model, but also each team’s relative strengths contributes meaningfully.</p>
<p>The final selected model is the Random Forest Classifier as it has a higher accuracy (0.698 vs 0.693) along with a higher F1-score (0.742 vs 0.739), indicating better balance between percision and recall, as well as higher AUC score (0.77 vs 0.76), making it more reliable in predicting both win and loss resutls.</p>
<p>With Random Forest Classifier as our model, we set a specific game, the “NFL 2024 game of the San Francisco 49ers vs the Washington Commanders” to provide an example of how our model could provide valuable insights.</p>
<p>Figure A, the plot shows how win probability of the home team (in this case, the Commanders) evovles throughout the game. At the start of the game (right hand side of the graph), the win probability is around 0.6 which is reasonable as we know that team strength affects the prediction quite significantly. As the game progresses, game state (e.g.&nbsp;score difference, field positions) changes and those changes influences the model’s prediction which is reflected in the fluctuation of the graph. Towards the end of the game (closer to gametime_remaning = 0) the win probability shifts to a more extreme value (0 or 1, in this case 0). This reflects a game state with a significant score difference of -17, limited time remaining and field position far away from the end zone (difficult to score a touchdown or a field goal), indicating there isn’t much chances for the Commanders to possibly win at that game state.</p>
<p>Figure B highlights the difference in distrbution of predicted win probabilities among the different quarters. In the early quarters, win probabilities centers around 0.6, reflecting high uncertainty due to ample remaining time. As the game progresses, the distribution spreads out in third quarter (a more uniform distribution). Another apprarent insight is how the win probabtility in the fourth quarter concentrates in the two extreme values of 0 and 1, indicating increased certainty in game outcome as it gets closer to the end of the game and score differences becomes more influential.</p>
<p>Figure C illustrates the relationship between win probabiltiy and gametime remaining, highlighting the role of team’s strength difference. At the early stages of the game, there are more extreme colour (purple or yellow) points towards the extreme values of 0 or 1, suggesting how the magnitude in strength difference influences the prediction of win probability. As the game progresses, the different colour points evens out, indicating that team strength difference doesn’t influence the win probabitliy as much as early in the game.</p>
</section>
<section id="conclusion-summary" class="level1">
<h1>CONCLUSION &amp; SUMMARY</h1>
<p>This project has developed a Random Forest Classifier Model tha predicts whether a home team will win an NFL game given the game state, and outputs the win probability at that point of the game. The most influiential features leveraged by the model are score difference, team strengths and game time remaining, as well as other less dominant features like field position also contribute in predicting the win probability.</p>
<p>The results shows that the model is able to produce meaningful and interpretable insights. For example, given a game state with significant negative score difference, limited time remaining and poor field position, the chances of winning are low and thus teams can take more risky plays to attempt to even out the score.</p>
<p>During model building, we also learn that a Random Forest Classifier performs slightly better than the XGBoost (by comparing the accuracy, F1-score and ROC-AUC). Hence, Random Forest Classifier was chosen as our final model with an accuracy of apprximately 70%.</p>
<p>However, there are several limitations to this method. First, the model doesn’t consider player statistics or whether they are playing or not, which can affect the offense or defense strength values, thus impacting game outcome. Besides that, the model doesn’t consider team performance against specific opponents, and there is no distinction between the offense and defense strengths beyond the overall strength value.</p>
<p>Further improvements would include adding more features such as players conditions, importing more hisotrical data to capture team performance against specific teams and differentiating offense and defense strengths.</p>
<p>To summarize, this project shows that machine learning models can effectively estimate win probability in NFL games using conditions of the game. These findings can be valuable for understanding game dynamics and supporting decision-making in sports analytics, while also providing a foundation for future improvements.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Copyright © 2026 Shannon Tanoto</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>